name: BungeeCordSystem
author: CodeReader
version: 1.0
main: de.codereader.main.Main
commands:
  bauserver:
  whereis:
  bc:
  cc:
  gcc:
  chatfilter:
  kick:
  notify:
  goto:
  wartung:
  getip:
  hub:
  report:
  reports:
  bewerben:
  getip:
  online:
  ping:
  server:
  shop:
  teamonline:
  ts:
  whereami:
  rank:
  l:
  lobby:
  h: